# docker-compose.yml

version: '3.8'

services:
  webapp:
    build: ./webapp
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./webapp/:/code
    ports:
      - 8001:8000
    networks:
    - timeseries-demo
    environment:
      PGHOST: ${PGHOST}
      PGUSER: ${PGUSER}
      PGPORT: ${PGPORT}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: $PGDATABASE

  datacollector:
    build: ./datacollector
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - timescaledb
    volumes:
      - ./datacollector/:/code
    ports:
      - 8002:8000
    environment:
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      WEATHER_API_URL: ${WEATHER_API_URL}
      ZIP_CODE: ${ZIP_CODE}
      PGHOST: ${PGHOST}
      PGUSER: ${PGUSER}
      PGPORT: ${PGPORT}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: $PGDATABASE
    networks:
    - timeseries-demo

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: password
    volumes:
      - /data/timescaledb:/var/lib/postgresql/data
    networks:
    - timeseries-demo

networks:
  timeseries-demo:
    driver: bridge