# docker-compose.yml

version: '3.8'

services:
  webapp:
    build: ./webapp
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./webapp/:/code
    ports:
      - 8001:8000

  datacollector:
    build: ./datacollector
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./datacollector/:/code
    ports:
      - 8002:8000   